version: '3.8'
services:
  gateway:
    build: ./gateway
    image: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - cache
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - REDIS_PORT=6379
      - REDIS_HOST=cache
  db:
    image: postgres:15.1-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  server:
    build: ./server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - "TZ=Asia/Dubai"
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
  cache:
    image: redis:7.0.8-alpine
    container_name: cache
    ports:
      - "6379:6379"