create table if not exists public.users
(
    user_id   bigint generated by default as identity
    primary key,
    email     varchar(255) not null
    constraint uk_6dotkott2kjsp8vw4d0m25fb7
    unique,
    user_name varchar(255) not null
    );

create table if not exists public.item_requests
(
    request_id          bigint generated by default as identity
    primary key,
    created             timestamp,
    request_description varchar(255),
    requester_id        bigint
    constraint fkc0xbt7if1ea0mmxksuv4ow7ay
    references public.users
    );

create table if not exists public.items
(
    item_id     bigint generated by default as identity
    primary key,
    available   boolean      not null,
    description varchar(255) not null,
    item_name   varchar(255) not null,
    owner_id    bigint       not null
    constraint fke37yi0i6rmaqcqickvb1vty22
    references public.users,
    request_id  bigint
    constraint fk1t697lh8cuvtdd4w9vjmodvw9
    references public.item_requests
    );

create table if not exists public.bookings
(
    booking_id bigint generated by default as identity
    primary key,
    end_time   timestamp,
    start_time timestamp,
    status     varchar(255),
    booker_id  bigint
    constraint fkc9bnqnreuuvddcscmp59fowih
    references public.users,
    item_id    bigint
    constraint fkbtv44e8p4a4pq8hfuakjbtfpc
    references public.items
    );

create table if not exists public.comments
(
    comment_id bigint generated by default as identity
    primary key,
    created    timestamp,
    text       varchar(255) not null,
    author_id  bigint
    constraint fkn2na60ukhs76ibtpt9burkm27
    references public.users,
    item_id    bigint       not null
    constraint fkkbkydvf8j8tfuego2iqxntwv2
    references public.items
    );